### ISSUE TITLE
Task 2 - Change Splash Screen

### ISSUE THREAD

**Issue by soumenkp2** [soumenkp2/resume_builder#20]
## Description
Change the vectors used inside splash screen and refactor the design by your own. 

## Skills
Dart , Flutter

## Expected project size
1-2 hours

## Difficulty
Easy

**Comment by UjjwalMahar** [comment]
@soumenkp2  please assign this issue to me under iwoc with appropriate difficulty tag.

**Comment by soumenkp2** [comment]
Hey @UjjwalMahar 
Have assigned the issue to you and tags are already appropriate as per IWOC guidelines. 
Thanks

**Comment by soumenkp2** [comment]
@UjjwalMahar 
Moreover I shall love to see some animations in the splash screen with this You can add some onboarding screens to give an initial review of the app.

**Comment by UjjwalMahar** [comment]
Please check for the Pr
