### ISSUE TITLE
📱 Better README File

### ISSUE THREAD

**Issue by Suryansh1720001** [soumenkp2/resume_builder#23]
Hello @soumenkp2 

**Is your feature request related to a problem? Please describe.**
### Features that I want to add

- Contributors details
- Project admin details
- Add the contributing line with a guideline link so that everyone motivates by that.
- Center heading for more attractive

**Describe the solution you'd like**

- Add new features

Kindly assign this issue to me under IWOC event with the label of medium.

**Comment by soumenkp2** [comment]
Hey @Suryansh1720001 
For now I am not looking to seek Doc contributions. 
So you may can select any of the issues which I have already opened specifically for the dev purpose. 

Thanks
